### ISSUE TITLE
Expected performance for just the decoding of the wheel.ts RAVE model

### ISSUE THREAD

**Issue by robclouth** [acids-ircam/nn_tilde#2]
On a powerful windows PC its running at 70% CPU across all 8 cores.
Profiling shows that 95% of the CPU time is spent in the openmp DLL. 

Is that just to be expected or is there some openmp build config I'm missing? It's a release build of course, O2 optimization.

**Comment by caillonantoine** [comment]
It really depends on the internal buffer size you are using. If you are using the 0 buffer mode, high usage is to be expected !
Increasing the buffer size in the external will reduce the CPU usage, at the expense of an increased latency.

**Comment by robclouth** [comment]
I'm using buffer 0 mode. Can you think of any areas that could be optimised? Does the fidelity affect the CPU load?

What latency is likely running it on the GPU? Could the latency be resolved with the shared cpu/GPU memory of an M1 chip?

**Comment by caillonantoine** [comment]
Some part of the code could be optimized (i.e [here](https://github.com/acids-ircam/nn_tilde/blob/master/src/frontend/maxmsp/nn_tilde/circular_buffer.h#L50)), but I don't think this is where the problem truly lies. Remember that we are dealing with a large CNN here, and that everything is performed on CPU, without being able to parallelize much of the process as you are using a very small buffer size. 

For now GPU computing is not supported, as I'm mainly using a M1 mac to develop the external. 

Fidelity won't change the computational load ! However you could decrease the capacity of the model during training in order to make it lighter. A RAVE model with capacity=5 for example runs in realtime on a raspberry pi 4 with a buffer size of 4096 !

**Comment by robclouth** [comment]
Yeah I saw that bit and considered vectorizing it but most of the processing comes from the network. I've seen some projects that somehow "flatten" the kernels or render them out somehow and save cycles like that. But I'm not really sure what that entails. There are a bunch of tricks for speeding up audio convolutions (partitioning etc) that might be not be used right now.

**Comment by caillonantoine** [comment]
yeah kernel flattening is useful for strictly auto-regressive networks, which is not the case here.
Partitioned convolutions would not help in our case given that we are using kernels whose size is at most 7.
